#%%
"""
# openTCAMV -- 11_concat_flows_along_time.py
If tracking itself was split across processes/machines by time range
(memory limits, cluster distribution -- not for speed; see `--workers` on
`10_conduct_tracking.py` for that), this script concatenates the resulting
`10_conduct_tracking.py` output files along the `time` axis to create a
single input file for `20_finalize_tracking.py`. Core logic lives in
`opentcamv.concat`; this script is a thin CLI driver.

## Data requirement
Input file: NetCDF files generated by `10_conduct_tracking.py`

## Example usage
$ python 11_concat_flows_along_time.py -t ../sample/2017_Lan_ns7_nt1_it0.000.nc ../sample/2017_Lan_ns7_nt1_it0.002.nc --exclude_texts concat -o ../sample/2017_Lan_ns7_nt1_concat.nc
$ python 11_concat_flows_along_time.py -g ../sample/2017_Lan_ns7_nt1_it*.nc --exclude_texts concat -o ../sample/2017_Lan_ns7_nt1_concat.nc

## Reference
Tsukada, T., Horinouchi, T., & Tsujino, S. (2024). Wind distribution in the eye of tropical cyclone revealed by a novel atmospheric motion vector derivation. Journal of Geophysical Research: Atmospheres, 129, e2023JD040585. https://doi.org/10.1029/2023JD040585
"""

import os
import logging
import argparse

import opentcamv

logger = logging.getLogger(__name__)
logging.basicConfig(
    level=logging.INFO, format="[%(asctime)s %(levelname)s %(name)s %(lineno)d] %(message)s", datefmt="%Y-%m-%d %H:%M:%S"
)
logger.info(f"PID: {os.getpid()}")


parser = argparse.ArgumentParser(description="Append netCDF files along `time` axis.")
parser.add_argument("-t", "--target", type=str, nargs="*", help="NetCDF filenames to concatenate")
parser.add_argument("-g", "--glob_strings", type=str, help="File pattern to match netCDF files")
parser.add_argument("-e", "--exclude_texts", type=str, nargs="+", help="Exclude the filenames including this text from concat list")
parser.add_argument("-d", "--drop_vars", type=str, nargs="+", help="Variable names included in the output file")
parser.add_argument("-o", "--oname", type=str, help="Output filename")

sample_dir = f"{os.path.dirname(__file__)}/../sample"
test_args = f"-g {sample_dir}/2017_Lan_ns7_nt1_it*.nc".split()

try:
    get_ipython().run_line_magic("load_ext", "autoreload")
    get_ipython().run_line_magic("autoreload", "2")
    args = parser.parse_args(test_args)
except NameError:
    args = parser.parse_args()

#%% Find files, concatenate, write
fnames = opentcamv.concat.resolve_filenames(args.target, args.glob_strings, args.exclude_texts)
logger.info(f"Found {len(fnames)} files")
for i, fname in enumerate(fnames):
    logger.info(f"Target {i}: {os.path.basename(fname)}")

all_ds = opentcamv.concat.concat_along_time(fnames.tolist(), args.drop_vars)

oname = args.oname or opentcamv.concat.default_oname(args.glob_strings)
all_ds.to_netcdf(oname)
logger.info(f"Saved to {oname}")
# %%
