#%%
"""
# openTCAMV -- 20_finalize_tracking.py
This script finalizes the tracking results by selecting the best solution from the candidate solutions.
The candidate solutions are generated by the script `10_conduct_tracking.py`.
Core logic lives in `opentcamv.finalize`; this script is a thin CLI driver.

## Data requirement
Input file: NetCDF files generated by `10_conduct_tracking.py`

## Usage
`ifns_rule` accepts a single file with an `omega` dimension (default `10_
conduct_tracking.py` output, `--omega` optional -- read from the file), a
`<ns>`-only placeholder for one such file per `ns` (`--omega` still
optional), or `<ns>`+`<omega>` placeholders for one file per (ns, omega)
pair (`--split_omega` `10_` output; `--omega` required there).

# Example 1
$ python 20_finalize_tracking.py ../sample/2017_Lan_ns7_nt1.nc --ns 7 --cthmax 10 --exclude stf stb score_ary psr -o ../sample/2017_Lan_ns7_nt1_ref.nc

# Example 2 (with reference flows to apply striations treatment using the result of Example 1)
$ python 20_finalize_tracking.py ../sample/2017_Lan_ns7_nt1.nc --ns 7 --cthmax 10 --exclude stf stb score_ary psr --ref_flows ../sample/2017_Lan_ns7_nt1_ref.nc --omega_stri 0.0015 -o ../sample/2017_Lan_ns7_nt1_final.nc

## Reference
Tsukada, T., Horinouchi, T., & Tsujino, S. (2024). Wind distribution in the eye of tropical cyclone revealed by a novel atmospheric motion vector derivation. Journal of Geophysical Research: Atmospheres, 129, e2023JD040585. https://doi.org/10.1029/2023JD040585
"""


import os
import logging
import argparse

import opentcamv.finalize as finalize

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="[%(asctime)s %(levelname)s %(name)s %(lineno)d] %(message)s", datefmt="%Y-%m-%d %H:%M:%S")
logger.info(f"PID: {os.getpid()}")


parser = argparse.ArgumentParser(description="Finalize tracking results")
parser.add_argument("ifns_rule", type=str, help="filename format, with <ns> as a placeholder for template size and (optionally) <omega> as a placeholder for Ω_i -- see module docstring for the three supported formats")
parser.add_argument("--ns", type=int, nargs="+", help="ns list")
parser.add_argument("--omega", type=str, nargs="+", help="Ω_i list. Required only when `ifns_rule` has a <omega> placeholder; otherwise read from each file's `omega` dimension (and cross-checked against this, if given)")
parser.add_argument("-o", "--ofn", type=str, help="output filename")
parser.add_argument("--itmin", type=int, default=0, help="minimum index of time dimension to consider")
parser.add_argument("--itmax", type=int, help="maximum index of time dimension to consider")
parser.add_argument("--itstep", type=int, default=1, help="step of time dimension to consider")
parser.add_argument("--Tw", type=float, default=1210, help="time period of median filtering window (in sec)")
parser.add_argument("--Hw", type=float, default=6, help="width & height of median filtering window for Cartesian grid (in km)")
parser.add_argument("--xw", type=float, help="x width of median filtering window for Cartesian grid (in km)")
parser.add_argument("--yw", type=float, help="y height of median filtering window for Cartesian grid (in km)")
parser.add_argument("--rw", type=float, default=6, help="r width of median filtering window for polar grid (in km)")
parser.add_argument("--aw", type=float, default=30, help="azimuth width of median filtering window for polar grid (in degree)")
parser.add_argument("--dth", type=float, default=10, help="threshold to limit the maximum d2 for rejection of candidates (in m/s)")
parser.add_argument("--dc", type=float, default=0.5, help="coefficient to be multiplied by the L2 norm of median wind speed for rejection of candidates (0: all rejected, 0.5: half length, 1: same length)")
parser.add_argument("--useV", action="store_true", help="if specified, use absolute wind speed for median filtering, not using each velocity component")
parser.add_argument("-e", "--max_epoch", type=float, default=20, help="the maximum number of epochs for updating the solutions")
parser.add_argument("--selector", type=str, default="iterative_median", choices=["iterative_median", "relaxation"], help="candidate-selection algorithm. `relaxation` (relaxation labeling) is not implemented yet")
parser.add_argument("--IRdiff", type=str, metavar="B13-B14", help="the formula for IR difference. It evaluates the difference between two variables parsed with a minus sign. The grid with |IR1-IR2| >= --dIR are masked")
parser.add_argument("--dIR", type=float, default=2, help="threshold to limit maximum IR difference (in K). The values larger than it will be masked.")
parser.add_argument("--cth", type=str, default="cth", help="cloud top height variable name")
parser.add_argument("--cthmin", type=float, help="threshold to limit the minimum cloud top height at initial position (in km)")
parser.add_argument("--cthmax", type=float, help="threshold to limit the maximum cloud top height at initial position (in km)")
parser.add_argument("--score_th", type=float, help="threshold to limit the minimum score of the candidates")
parser.add_argument("--out_final_omega", action="store_true", help="output `final_omega` which is the used omega values in final solutions")
parser.add_argument("--out_final_ns", action="store_true", help="output `final_ns` which is the used ns in final solutions")
parser.add_argument("--out_final_medians", action="store_true", help="output `final_medians` which is the final median wind speeds")
parser.add_argument("--priority", type=str, default="score", choices=["score","dangv"], help="priority for selecting the best solution. `score` selects the solution with the highest score. `dangv` selects the solution with the smallest angular velocity difference from the reference angular velocity")
parser.add_argument("--exclude", type=str, nargs="*", default=[], help="drop specified variables from the final output file")
parser.add_argument("--ref_flows", type=str, help="Reference flows to apply omega_stri procedure")
parser.add_argument("--tau_stri", type=int, default=24, help="temporal window size (in index space) to compute the velocity contrast of --ref_flows for detection of striations")
parser.add_argument("--v_stri", type=float, default=20, help="threshold to limit the maximum velocity contrast for detection of striations (m/s)")
parser.add_argument("--cth_stri", type=int, help="threshold to limit the maximum cloud top height to get reference contrast")
parser.add_argument("--omega_stri", type=float, default=0.0, help="threshold to limit the minimum Ω_i for the striation grids (rad/s)")

# sample
sample_dir = f"{os.path.dirname(__file__)}/../sample"
test_args = f"{sample_dir}/2017_Lan_ns7_nt1.nc --ns=7 --cthmax=10 --exclude stf stb score_ary psr -o={sample_dir}/2017_Lan_ns7_nt1_ref.nc".split()
# test_args = f"{sample_dir}/2017_Lan_ns7_nt1.nc --ns=7 --cthmax=10 --exclude stf stb score_ary psr --ref_flows={sample_dir}/2017_Lan_ns7_nt1_ref.nc --omega_stri=0.0015 -o {sample_dir}/2017_Lan_ns7_nt1_final.nc".split()

try:
    get_ipython().run_line_magic("load_ext", "autoreload")
    get_ipython().run_line_magic("autoreload", "2")
    args = parser.parse_args(test_args)
except NameError:
    args = parser.parse_args()

#%% Run
final_flows = finalize.run(args)
final_flows = finalize.format_for_write(final_flows)
final_flows.to_netcdf(args.ofn)
logger.info(f"[SUCCESS] {args.ofn}")
#%%
